/* Generated by the Systemtap dtrace wrapper */

#define STAP_HAS_SEMAPHORES 1


#include <sys/sdt.h>

/* HEAPSORT_INPUT_START () */
#define HEAPSORT_INPUT_START_ENABLED() input_start_semaphore
__extension__ extern unsigned short input_start_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define HEAPSORT_INPUT_START() \
STAP_PROBE(provider,input_start)

/* HEAPSORT_INPUT_DONE ( int) */
#define HEAPSORT_INPUT_DONE_ENABLED() input_done_semaphore
__extension__ extern unsigned short input_done_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define HEAPSORT_INPUT_DONE(arg1) \
STAP_PROBE1(provider,input_done,arg1)

/* HEAPSORT_BUFFER_RESIZE_START () */
#define HEAPSORT_BUFFER_RESIZE_START_ENABLED() buffer_resize_start_semaphore
__extension__ extern unsigned short buffer_resize_start_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define HEAPSORT_BUFFER_RESIZE_START() \
STAP_PROBE(provider,buffer_resize_start)

/* HEAPSORT_BUFFER_RESIZE_DONE () */
#define HEAPSORT_BUFFER_RESIZE_DONE_ENABLED() buffer_resize_done_semaphore
__extension__ extern unsigned short buffer_resize_done_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define HEAPSORT_BUFFER_RESIZE_DONE() \
STAP_PROBE(provider,buffer_resize_done)

/* HEAPSORT_OUTPUT_START ( int) */
#define HEAPSORT_OUTPUT_START_ENABLED() output_start_semaphore
__extension__ extern unsigned short output_start_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define HEAPSORT_OUTPUT_START(arg1) \
STAP_PROBE1(provider,output_start,arg1)

/* HEAPSORT_OUTPUT_DONE () */
#define HEAPSORT_OUTPUT_DONE_ENABLED() output_done_semaphore
__extension__ extern unsigned short output_done_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define HEAPSORT_OUTPUT_DONE() \
STAP_PROBE(provider,output_done)

/* HEAPSORT_HEAP_PLACE ( int, int) */
#define HEAPSORT_HEAP_PLACE_ENABLED() heap_place_semaphore
__extension__ extern unsigned short heap_place_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define HEAPSORT_HEAP_PLACE(arg1,arg2) \
STAP_PROBE2(provider,heap_place,arg1,arg2)

/* HEAPSORT_HEAP_BUILD_START () */
#define HEAPSORT_HEAP_BUILD_START_ENABLED() heap_build_start_semaphore
__extension__ extern unsigned short heap_build_start_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define HEAPSORT_HEAP_BUILD_START() \
STAP_PROBE(provider,heap_build_start)

/* HEAPSORT_HEAP_BUILD_DONE () */
#define HEAPSORT_HEAP_BUILD_DONE_ENABLED() heap_build_done_semaphore
__extension__ extern unsigned short heap_build_done_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define HEAPSORT_HEAP_BUILD_DONE() \
STAP_PROBE(provider,heap_build_done)

